### ISSUE TITLE
Transfer repo to the xarray-contrib

### ISSUE THREAD

**Issue by andersy005** [xarray-contrib/cupy-xarray#1]
Thank you for setting this up, @jacobtomlinson! I'd like to help out with ironing out some of the details/development of cupy-xarray. In light of @tomchor's https://github.com/pydata/xarray/issues/4212#issuecomment-775284567, I'm wondering if you would be interested in transferring this repo over to the @xarray-contrib org to increase visibility?

**Comment by quasiben** [comment]
I suspect @jacobtomlinson would good with transferring.  FYI, he's out on PTO for the next week

**Comment by andersy005** [comment]
👍🏽 Awesome!

> I suspect @jacobtomlinson would be good with transferring. FYI, he's out on PTO for the next week

@quasiben, Thank you for the heads-up. I'll wait until he's back from PTO.

**Comment by jacobtomlinson** [comment]
I'm around again now. I'd be happy to move this somewhere else. When creating it I was unsure if @xarray-contrib or @rapids was more appropriate. Perhaps @quasiben can advise?

**Comment by quasiben** [comment]
This living in xarray-contrib I think makes sense

**Comment by jacobtomlinson** [comment]
Ok great let's do it!

I don't have permission to make the transfer, so I think I either need to be added to the @xarray-contrib org or I'll need to transfer the repo to someone else who is, then they can transfer it.

What do you suggest @andersy005?

**Comment by andersy005** [comment]
@jacobtomlinson, I have permission to make the transfer. Feel free to transfer it to me and then I will complete the transfer.

**Comment by jakirkham** [comment]
Is there a way to give Jacob and possibly others permissions after this is transferred?

**Comment by andersy005** [comment]
> Is there a way to give Jacob and possibly others permissions after this is transferred? 

👍🏽 Happy to take care of this once the transfer is complete. Apart from (@jakirkham, @quasiben, @jacobtomlinson), please let me know whom I should add as collaborators.

**Comment by jacobtomlinson** [comment]
Thanks @andersy005. I've started the transfer so you should have an email.

**Comment by andersy005** [comment]
Thank you, Jacob! The transfer is complete. You should have admin access. I sent invites to @quasiben and @jakirkham

**Comment by jakirkham** [comment]
Thanks Anderson! 😄 

FWIW invites can also be found at: https://github.com/xarray-contrib/cupy-xarray/invitations

**Comment by jacobtomlinson** [comment]
Thanks @andersy005 I guess we can close this!
