### ISSUE TITLE
Update Documentations

### ISSUE THREAD

**Issue by negin513** [xarray-contrib/cupy-xarray#33]
@dcherian and I brainstormed on the topics that should be included in the docs as following:

1. Basic Concepts : 
* How to convert numpy and cupy. 
* `.mean` , `.std` and basic operations. 
* [Creating Arrays](https://cupy-xarray.readthedocs.io/quickstart.html#creating-arrays)
* [Checking for cupy arrays](https://cupy-xarray.readthedocs.io/quickstart.html#checking-for-cupy-arrays)
* [Accessing the underlying array](https://cupy-xarray.readthedocs.io/quickstart.html#accessing-the-underlying-array)
* [Moving data between CPU and GPU (or host and device)](https://cupy-xarray.readthedocs.io/quickstart.html#moving-data-between-cpu-and-gpu-or-host-and-device)

2. Fundamental Xarray + Cupy:
* [Most Xarray operations preserve array type](https://cupy-xarray.readthedocs.io/quickstart.html#most-xarray-operations-preserve-array-type)
* [Alignment](https://cupy-xarray.readthedocs.io/quickstart.html#alignment)
* [Broadcasting](https://cupy-xarray.readthedocs.io/quickstart.html#broadcasting)
* [Basic Arithmetic](https://cupy-xarray.readthedocs.io/quickstart.html#basic-arithmetic)
* [Numpy universal functions](https://cupy-xarray.readthedocs.io/quickstart.html#numpy-universal-functions)

3. [High-level Xarray functions](https://cupy-xarray.readthedocs.io/quickstart.html#high-level-xarray-functions)
* [Groupby works](https://cupy-xarray.readthedocs.io/quickstart.html#groupby-works)
* [Rolling windows do not work](https://cupy-xarray.readthedocs.io/quickstart.html#rolling-windows-do-not-work)
* [Weighted operations work](https://cupy-xarray.readthedocs.io/quickstart.html#weighted-operations-work)

Make the docs as notebooks.

**Comment by jacobtomlinson** [comment]
I'm not sure I understand this issue. What are you asking here?

**Comment by weiji14** [comment]
Assuming that this is done with #35, so closing.
