### ISSUE TITLE
Naive question

### ISSUE THREAD

**Issue by MordicusEtCubitus** [xarray-contrib/cupy-xarray#38]
Could the new dask backend using cupy implements by itself the cupy-xarray machinery ?

~~~python
%%time
import dask.array as da
import cupy as cp
import dask
cp.cuda.Device(0).use()
with dask.config.set({"array.backend": "cupy"}):
    x = da.random.normal(10,1, (100_000, 100_000), chunks=(10_000, 2000))
    y = x.mean(axis=0)[::100]
    z = y.compute()
    print(z.shape, type(z))
~~~

Or is it too naive and xarray is using numpy directly at many places in the code ?

Gaël,

**Comment by dcherian** [comment]
Thanks @keewis 

@MordicusEtCubitus I think this discussion belongs elsewhere. There is no xarray in your example! :)

**Comment by MordicusEtCubitus** [comment]
No, keewis properly replied. Indeed, I should have add an xarray code below `with dask.config.set({"array.backend": "cupy"})`
