### ISSUE TITLE
Problem importing DuckArrayModule

### ISSUE THREAD

**Issue by saishashank85** [xarray-contrib/cupy-xarray#41]
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In [13], line 4
      2 import pandas as pd
      3 import xarray as xr
----> 4 import cupy_xarray 
      5 xr.set_options(display_expand_data=False)
      7 rng = np.random.default_rng(seed=0)  # we'll use this later

File /usr/local/lib/python3.9/dist-packages/cupy_xarray/__init__.py:2
      1 from . import _version
----> 2 from .accessors import CupyDataArrayAccessor, CupyDatasetAccessor  # noqa
      4 __version__ = _version.get_versions()["version"]

File /usr/local/lib/python3.9/dist-packages/cupy_xarray/accessors.py:8
      1 import cupy as cp
      2 from xarray import (
      3     DataArray,
      4     Dataset,
      5     register_dataarray_accessor,
      6     register_dataset_accessor,
      7 )
----> 8 from xarray.core.pycompat import DuckArrayModule
     10 dsk = DuckArrayModule("dask")
     11 dask_array_type = dsk.type

ModuleNotFoundError: No module named 'xarray.core.pycompat'

As i check from the xarray module. 
The DuckArrayModule is present in xarray/namedarray/pycompat.py and not in core. 

Also im not installing cupy from requirements since i've already installed cupy-cuda11x as per my cuda version.

**Comment by negin513** [comment]
resolved with #42
