### ISSUE TITLE
add API to docs build

### ISSUE THREAD

**Issue by dcherian** [xarray-contrib/cupy-xarray#5]
autodoc/autosummary import the package to automatically add the docstrings.

This means cupy-xarray and cupy are imported. importing cupy fails on RTD saying it can't find libcuda.

It'd be nice to find a workaround. 

Worst case, I guess we can run autodoc locally and then push the generated html?

(note that installing cuda brings in cudatoolkit which is a 800MB download; it'd be nice to just not do that)

**Comment by dcherian** [comment]
@keewis, @andersy005 Do either of you have an opinion on how to proceed?

**Comment by keewis** [comment]
RTD [recommends](https://docs.readthedocs.io/en/stable/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules) mocking libraries that you can't install easily, maybe that's worth investigating?

**Comment by keewis** [comment]
otherwise, since I just saw that `cupy` is using RTD as well, you might be able to copy their setup?

cc @jacobtomlinson

**Comment by jacobtomlinson** [comment]
@leofang do you have any quick advice on building sphinx docs for RTD for cupy without having to install everything?

**Comment by leofang** [comment]
I see. I'd suggest to build a "NO CUDA" CuPy in your RTD env, and then `import cupy`. They tailored this option specifically for RTD to use it to generate docs. See https://github.com/cupy/cupy/blob/9d439227f1a53bbd9ebb16784e40bcce44bc8042/.github/workflows/pretest.yml#L37-L41

**Comment by weiji14** [comment]
Looks like CuPy 13 now supports lazy import (https://github.com/cupy/cupy/issues/7620), and there is a `cupy-core` package on `conda-forge` that doesn't require CUDA (https://github.com/conda-forge/cupy-feedstock/issues/229#issuecomment-1905162534)! I've opened a PR at #44 to render the API docs.
