### ISSUE TITLE
Flexibility in requirements/dependencies

### ISSUE THREAD

**Issue by miguelcarcamov** [xarray-contrib/cupy-xarray#55]
Currently the cupy-xarray package depends on the last version of cupy. This means that if an user has an older version of cupy, cupy will be installed again (which takes a lot of time). Would if be possible to put some flexibility in the pyproject.toml file and use >= or <= for cupy's versions?

**Comment by weiji14** [comment]
Hmm, I don't see an explicit minimum version of `cupy` set here, only for xarray:

https://github.com/xarray-contrib/cupy-xarray/blob/a46029529a08adfb07b4130452257c819d8b0523/pyproject.toml#L17-L20

What command are you running that is causing your system to pull in the latest version of cupy?

**Comment by weiji14** [comment]
Assuming that you've managed to handle the cupy version issue, so closing this now. Let us know if this needs to be re-opened.
