### ISSUE TITLE
General function to convert from np.array dask dataset to cupy dask dataset

### ISSUE THREAD

**Issue by miguelcarcamov** [xarray-contrib/cupy-xarray#57]
I'm building a module where the user can choose if their arrays run on CPU or GPU using dask. This is done by running `dask.config.set({"array.backend": "cupy"})`. Additionally, if the backend is set to cupy I want to convert the xarray dataset arrays to cupy as well using cupy_xarray.

In my project the `cupy` and `cupy-xarray` packages are optional.

Therefore if `cupy` and `cupy-xarray` are not installed and the user sets the backend to `numpy` the following code will fail.

```python
import cupy_xarray # This will fail if cupy_xarray is not found
import dask
import xarray


def xarray_dataset_as_cupy(dataset: xarray.Dataset = None):
    if dask.config.get("array.backend") == "cupy" and dataset is not None:
        return dataset.as_cupy() # If cupy_xarray is not imported then as_cupy() function will fail
    else:
        return dataset

```

- I guess I can use a `try except` in order to import `cupy_xarray`. However if I do that the as_cupy() function will fail as well because it will not be registered.

Any ideas on how to solve this?

**Comment by jacobtomlinson** [comment]
I would do something like this.

```python
import dask
import xarray

try:
    import cupy_xarray
except ImportError:
    cupy_xarray = None


def xarray_dataset_as_cupy(dataset: xarray.Dataset = None):
    if cupy_xarray and dask.config.get("array.backend") == "cupy" and dataset is not None:
        return dataset.as_cupy()
    else:
        return dataset
```

**Comment by miguelcarcamov** [comment]
Awesome, thanks :)
